purple:
  king:
    - x: 6
      y: 0
  knight:
    - x: 8
      y: 0
    - x: 9
      y: 0
  archer:
    - x: 4
      y: 0
    - x: 3
      y: 0

orange:
  king:
    - x: 5
      y: 11
  knight:
    - x: 3
      y: 11
    - x: 2
      y: 11
  archer:
    - x: 7
      y: 11
    - x: 8
      y: 11