purple:
  king:
    - x: 0
      y: 0
  knight:
    - x: 0
      y: 3
  archer:
    - x: 0
      y: 2

orange:
  king:
    - x: 11
      y: 11
  knight:
    - x: 10
      y: 11
  archer:
    - x: 9
      y: 11

